# Generated by Django 3.1.2 on 2021-03-07 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало действия промокода')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец действия промокода')),
                ('max_users_count', models.IntegerField(verbose_name='Начальное количество пользователей')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.brand', verbose_name='Бренд')),
                ('users', models.ManyToManyField(blank=True, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, использующие промокод')),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Название')),
                ('image', models.ImageField(upload_to=service.models.get_border_path, verbose_name='Изображение')),
                ('colorable', models.BooleanField(default=False, verbose_name='Изменяем ли цвет')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.brand', verbose_name='Организация')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.code', verbose_name='Промокод')),
            ],
        ),
    ]
